

title: Machine Learning Opportunities in Public Health

remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false

heading_anchors: true
permalink: pretty
nav_sort: case_insensitive # default, equivalent to nil
back_to_top: true
back_to_top_text: "Back to top"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false


footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
