title: Machine Learning in Public and Population Health
url: https://chunaralab.github.io/MLPH/
description: Get in touch with us at rumi.chunara@nyu.edu, yuan.zhao@nyu.edu, vishwalim@nyu.edu 
#remote_theme: pmarsceill/just-the-docs
theme: jekyll-theme-cayman

#color_scheme: "light"
search_enabled: false

heading_anchors: true
permalink: pretty
nav_sort: case_insensitive # default, equivalent to nil
back_to_top: true
back_to_top_text: "Back to top"

