

title: Machine Learning Opportunities in Public Health
baseurl: "/MLPH" # the subpath of your site, e.g. /blog
url: "https://ChunaraLab.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: pmarsceill/just-the-docs
