

#title: Machine Learning Opportunities in Public Health
remote_theme: pmarsceill/just-the-docs


color_scheme: "light"
search_enabled: false

heading_anchors: true
permalink: pretty
nav_sort: case_insensitive # default, equivalent to nil
back_to_top: true
back_to_top_text: "Back to top"


display: block
