

title: Machine Learning Opportunities in Public Health
url: https://chunaralab.github.io/MLPH/
description: Get in touch at rumi.chunara@nyu.edu or yuan.zhao@nyu.edu or vishwalim@nyu.edu 
#remote_theme: pmarsceill/just-the-docs
theme: jekyll-theme-cayman

#color_scheme: "light"
search_enabled: false

heading_anchors: true
permalink: pretty
nav_sort: case_insensitive # default, equivalent to nil
back_to_top: true
back_to_top_text: "Back to top"

