

title: Machine Learning Opportunities in Public Health
url: "https://ChunaraLab.github.io/MLPH/" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: pmarsceill/just-the-docs
